-- ============================================================
-- GPR — schéma de base (reconstitué depuis le projet Supabase cloud,
-- via l'introspection des colonnes utilisées par le code applicatif).
-- Sert uniquement au stack Supabase LOCAL (Docker) pour le développement/test.
-- ============================================================

create table sites (
  id bigint generated by default as identity primary key,
  nom text not null,
  type text not null check (type in ('central','detachement','reserve')),
  created_at timestamptz not null default now()
);

create table roles (
  id bigint generated by default as identity primary key,
  nom text not null unique
);

create table utilisateurs (
  id bigint generated by default as identity primary key,
  nom text not null,
  prenom text not null,
  email text not null unique,
  role_id bigint not null references roles(id),
  site_id bigint references sites(id),
  auth_id uuid unique references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table types_vehicules (
  id bigint generated by default as identity primary key,
  nom text not null,
  marque text
);

create table pieces (
  id bigint generated by default as identity primary key,
  nom text not null,
  categorie text,
  type_vehicule_id bigint references types_vehicules(id),
  reference text,
  created_at timestamptz not null default now()
);

create table stocks (
  id bigint generated by default as identity primary key,
  piece_id bigint not null references pieces(id),
  site_id bigint not null references sites(id),
  quantite numeric not null default 0,
  seuil_alerte numeric not null default 0,
  unique (piece_id, site_id)
);

create table vehicules (
  id bigint generated by default as identity primary key,
  immatriculation text not null,
  statut text not null default 'arrive',
  type_vehicule_id bigint references types_vehicules(id),
  site_id bigint not null references sites(id)
);

create table pieces_utilisees (
  id bigint generated by default as identity primary key,
  vehicule_id bigint not null references vehicules(id),
  piece_id bigint not null references pieces(id),
  quantite numeric not null,
  date_utilisation date not null,
  utilisateur_nom text
);

create table demandes_pieces (
  id bigint generated by default as identity primary key,
  piece_id bigint not null references pieces(id),
  quantite numeric not null,
  demandeur_nom text,
  demandeur_id bigint references utilisateurs(id),
  statut text not null default 'en_attente',
  vehicule_nom text,
  vehicule_id bigint references vehicules(id),
  site_id bigint references sites(id),
  date_demande date not null
);

create table carburant_stock (
  id bigint generated by default as identity primary key,
  site_id bigint not null references sites(id),
  type text not null check (type in ('gasoil','essence')),
  quantite_litres numeric not null default 0,
  unique (site_id, type)
);

create table mouvements_carburant (
  id bigint generated by default as identity primary key,
  site_id bigint not null references sites(id),
  type text not null check (type in ('gasoil','essence')),
  mouvement text not null check (mouvement in ('ravitaillement','consommation')),
  quantite_litres numeric not null,
  date_mouvement timestamptz not null default now(),
  utilisateur_id bigint references utilisateurs(id)
);
